name: google-java-format
on: [ pull_request ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --aosp"
          commit-message: "style: reformat by google-java-format"