name: Format
on: [ pull_request ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "style: reformat by google-java-format"